### ISSUE TITLE
Xcode 8 and Google maps error with Swift3

### ISSUE THREAD

**Issue by rakeshbiswalmobileprogrmming** [googlemaps/hellomap-ios#2]
I am using Google maps in my project which was working fine while using Xcode 7.3 but recently i have updated my XCode to 8th version so now while i am trying to open the project a popup appears asking me to convert the project to Swift 3.0 version and when convert it, the project generates lots of errors in all the .swift file.
i am using cocoapods for Google Maps. here are the pods i am using :

  pod 'Google/SignIn'
  pod 'GooglePlaces'
  pod 'GoogleMaps'
can anyone tell me why the errors appear and how to resolve those errors, or are there any other pods which support swift 3.0 version.?

**Comment by domesticmouse** [comment]
GoogleMaps and GooglePlaces are both usable from Swift 3.0. However, the couple of attempts I made to automatically convert a project from Swift 2.x to Swift 3.0 resulted in broken Swift code.

I'd suggest you start with a new Swift 3 project for starters while you learn your way around the new API changes that Apple made in the transition from Swift 2 to Swift 3.

**Comment by AnkiReddyPolu** [comment]
Hi i am using google map api for places, maps, geocoder and api also. before it is working but now it not working i have search for places it is displaying for can't load search results please solve the problem.
![whatsapp image 2017-08-24 at 16 32 38](https://user-images.githubusercontent.com/29113492/29663680-f5d92596-88e9-11e7-98cf-7e506885f3f4.jpeg)

**Comment by domesticmouse** [comment]
I can't debug this from the little information you have supplied. I suggest you:
1. Run the sample app for Place Picker: `pod try GooglePlacePicker`
1. Confirm your API Key is working by looking at the log output
1. Upload a minimal reproduction case to GitHub and raise a ticket on our [Issue Tracker](https://developers.google.com/maps/support/#issue_tracker).
